[package]
name = "nbrg"
version = "0.1.0"
authors = ["Masanori Kanazu <mknz@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
regex = "1"
serde_json = "1.0"
walkdir = "2"
